### ISSUE TITLE
Native english language, GPU support through SiaNet

### ISSUE THREAD

**Issue by ad48hp** [ColorfulSoft/StyleTransfer-Colorization-SuperResolution#7]
Could you change the repository & subsequently the applications to be both in English & Russia ?
(I could once look at porting the application together with English buttons/labels textzz)

But what i think i couldn't do myself yet (or could pretty hardly) is porting it to supporing GPUs, which could be done by porting it to this framework..
https://github.com/SciSharp/SiaNet

**Comment by GlebSBrykin** [comment]
Good day, sorry for the long wait! English will soon be added as a separate branch. Regarding the GPU, I plan to call the OpenCL driver directly from the application via PInvoke. This will allow you to use almost all video cards that are younger than 15 years and different from NVIDIA. It's not that hard to do. Especially as to calculate on GPU makes sense only convolutions as they demand really a lot of calculations. As for other layers, such as pooling and relu, the use of the GPU there can not lead to higher performance.

**Comment by ad48hp** [comment]
I had poorly settled notifications, so i didn't even noticed the response, so i yet didn't mind the wait..
I also had a quite silly idea, could you implement the DeepFakes (face swap) for videos software in .NET ? Thought that the Tensorflow.NET or other pre-made libraries would make it easier to code for you, as you wouldn't have to pretty much rewrite the conv code from scratch each time you create a project..

I would a little bit recommend to try w/ this one, but it will be probably challenin', and also the code seems to be incomplete so far..
https://github.com/shoutOutYangJie/Few-Shot-Adversarial-Learning-for-face-swap

**Comment by GlebSBrykin** [comment]
That's an interesting idea. Theoretically, it is possible, but first I need to implement GPU support, otherwise the program will be very slow. To use an unmanaged library, such as tensorflow, I don't want. There are several objective reasons, if necessary, I can tell you about them. I can't promise anything yet.

**Comment by ad48hp** [comment]
Maybe we shall collaborate a bit yet..
I think yet i'm maybe pretty terrible at makin' ML code work (in any programming language..), while ya quite fall short on the Windows Form design.. Do you have any account accepting PMs outside of Github ?

**Comment by GlebSBrykin** [comment]
You can write me a mail glebbrykin@yandex.ru.

**Comment by jdluzen** [comment]
I would like to help try to port this project to some kind of GPU accelerated code. I quickly attempted to use https://github.com/kaby76/Campy but it crashed, and wasn't able to move forward with it really. Really impressive project though.

Your project has been the ONLY project that has really helped me to understand ML in general. Every other one has been too much of a black box. Thank you so much for an amazing collection of work!

**Comment by GlebSBrykin** [comment]
Thank you very much for your support! I plan to use OpenCL to work with the GPU. This will allow to use not only the card from NVIDIA, but also any other.
