### ISSUE TITLE
ability to save generated images 

### ISSUE THREAD

**Issue by mcDandy** [ColorfulSoft/StyleTransfer-Colorization-SuperResolution#9]
It would be good if you could batch enhance and save photos.

**Comment by GlebSBrykin** [comment]
At the moment, this does not make sense, since the processing of a single image takes quite a long time. In the future, when GPU support is added, the batch processing capability will be implemented.

**Comment by mcDandy** [comment]
Thank you

Dne ne 13. říj 2019 17:44 uživatel Глеб Брыкин <notifications@github.com>
napsal:
